before_script:
  - apt-get update
  - apt-get -y install ant
  - apt-get -y install ivy
  - cp /usr/share/java/ivy.jar /usr/share/ant/lib/

stages:        # List of stages for jobs, and their order of execution
  - .pre
  - build
  - test
  - docs
  - run


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ant -version
    - ant dist

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."
    - ant test-reports

doc-job:   # This job also runs in the test stage.
  image: openjdk:11
  stage: docs    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "documentation generation..."
    - ant javadoc

run-job:      # This job runs in the deploy stage.
  stage: run  # It only runs when both jobs in the test stage complete successfully.
  script:
    - echo "Deploying application....."
    - ant run